// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABF0yZxD4GHOcEQ7tBT0KmWHMHZXePyIs',
    appId: '1:688536617814:web:963394bf73814e11b1ccf7',
    messagingSenderId: '688536617814',
    projectId: 'tank-controller-c9912',
    authDomain: 'tank-controller-c9912.firebaseapp.com',
    storageBucket: 'tank-controller-c9912.firebasestorage.app',
    measurementId: 'G-4TGFZQ4KYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhwkh8m0Cy7Mpe6BRDjgmhCFLVP-lK1uk',
    appId: '1:688536617814:android:34c63db6fda8de3db1ccf7',
    messagingSenderId: '688536617814',
    projectId: 'tank-controller-c9912',
    storageBucket: 'tank-controller-c9912.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpsJyanCJA7Eu81sI-9mU-l3ut3E8v9Ys',
    appId: '1:688536617814:ios:9f479a50aaa3c367b1ccf7',
    messagingSenderId: '688536617814',
    projectId: 'tank-controller-c9912',
    storageBucket: 'tank-controller-c9912.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpsJyanCJA7Eu81sI-9mU-l3ut3E8v9Ys',
    appId: '1:688536617814:ios:9f479a50aaa3c367b1ccf7',
    messagingSenderId: '688536617814',
    projectId: 'tank-controller-c9912',
    storageBucket: 'tank-controller-c9912.firebasestorage.app',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABF0yZxD4GHOcEQ7tBT0KmWHMHZXePyIs',
    appId: '1:688536617814:web:b0015fb92ea0dfa8b1ccf7',
    messagingSenderId: '688536617814',
    projectId: 'tank-controller-c9912',
    authDomain: 'tank-controller-c9912.firebaseapp.com',
    storageBucket: 'tank-controller-c9912.firebasestorage.app',
    measurementId: 'G-YC6K5389CP',
  );
}
